# Generated by Django 2.2.2 on 2022-01-14 02:29

import accounts.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(error_messages={'unique': 'A user with that user_id already exists.'}, help_text='ユーザーIDは一意です。英数字と_(アンダースコア)のみが使用できます。', max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3, '3文字以上です！'), django.core.validators.RegexValidator('^[a-zA-Z0-9_]*$', '英数字と_(アンダースコア)のみです！')], verbose_name='ユーザーID')),
                ('user_name', models.CharField(max_length=30, verbose_name='ユーザー名')),
                ('email', models.EmailField(help_text='入力されたメールアドレスに確認メールが送信されます。', max_length=254, unique=True, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(default=None, max_length=20, null=True, unique=True, verbose_name='電話番号')),
                ('birth', models.DateField(default=datetime.date(2022, 1, 14), verbose_name='生年月日')),
                ('political_faction', models.CharField(max_length=20, verbose_name='党派')),
                ('icon_photo', models.ImageField(default='default.jpg', upload_to='', verbose_name='アイコン写真')),
                ('bio', models.TextField(max_length=150, verbose_name='ひとこと')),
                ('assembly', models.BooleanField(default=False, verbose_name='議員')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'ユーザー',
            },
            managers=[
                ('objects', accounts.models.MyUserManager()),
            ],
        ),
    ]
