# Generated by Django 2.2.2 on 2022-01-14 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='カテゴリ名')),
            ],
            options={
                'verbose_name_plural': 'カテゴリテーブル',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chatroom_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='チャットルームID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name_plural': 'チャット(部屋)テーブル',
            },
        ),
        migrations.CreateModel(
            name='ChatDetail',
            fields=[
                ('chat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='チャット詳細ID')),
                ('content', models.TextField(verbose_name='投稿内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('chatroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fabla.Chat', verbose_name='チャットルームID')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name_plural': 'チャット(詳細)テーブル',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='コメントID')),
                ('content', models.TextField(verbose_name='コメント内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name_plural': 'コメントテーブル',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='投稿ID')),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='写真')),
                ('hide_reason', models.TextField(blank=True, verbose_name='伏字化理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('category_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_fabla.Category', verbose_name='カテゴリ番号')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name_plural': '投稿テーブル',
            },
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.TextField(verbose_name='通報理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fabla.Post', verbose_name='投稿ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name_plural': '投稿通報テーブル',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='登録日時')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fabla.Post', verbose_name='投稿ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name_plural': 'イイネテーブル',
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.TextField(verbose_name='通報理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fabla.Comment', verbose_name='コメントID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name_plural': 'コメント通報テーブル',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fabla.Post', verbose_name='投稿ID'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.CreateModel(
            name='Checked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fabla.Post', verbose_name='投稿ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name_plural': '既読テーブル',
            },
        ),
        migrations.CreateModel(
            name='ChatReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.TextField(verbose_name='通報理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fabla.ChatDetail', verbose_name='チャット詳細ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name_plural': 'チャット通報テーブル',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fabla.Post', verbose_name='投稿ID'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user1_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID_議員'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user2_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normal_user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID_一般'),
        ),
    ]
