@startuml クラス図
' 公開 (+)
' 非公開 (-)
' 保護 (#)
' パッケージ (~)
' 派生 (/)
' 静的 (下線)
class "ユーザクラス" as userclass {
  - メールアドレス
  - 名前
  - 生年月日
  - 事務所の電話番号
  - 
  - 卒業年月日

  + 新規登録する()
  + 専門分野を決める()
  + 卒業する()
}

object "学生オブジェクト" as StudentObj {
  - 学生ID : 112233
  - 名前 : 田中太郎
  - 生年月日 : 19880601
  - 専門分野 : セキュリティ
  - 入学年月日 : 20040401
  - 卒業年月日 : 19860707

  + 入学する()
  + 専門分野を決める()
  + 卒業する()
}
@enduml